/*
 * This source file was generated by the Gradle 'init' task
 */
package practice.kotlin.app

internal object MessageUtils {
    @Suppress("FunctionOnlyReturningConstant")
    fun getMessage(): String = "Hello      World!"
}
