name: Build and test on push

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  gradle-build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew build
      - run: ./gradlew test

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - name: Generate and submit dependency graph
        # cf: https://github.com/gradle/actions/blob/main/docs/dependency-submission.md
        uses: gradle/actions/dependency-submission@v4
